name = "datamine"
version = "0.1.0"

description = "Minecraft data in Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "zwubs", repo = "datamine" }

[dependencies]
gleam_stdlib = ">= 0.54.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.3.0 and < 2.0.0"
glam = ">= 2.0.2 and < 3.0.0"
simplifile = ">= 2.2.1 and < 3.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"
gleam_httpc = ">= 4.1.0 and < 5.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"
