name = "datamine"
version = "0.1.0"

description = "Minecraft data in Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "zwubs", repo = "datamine" }

[dependencies]
gleam_stdlib = ">= 0.54.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.3.0 and < 2.0.0"
